"""
Blueprint Generator for Unified Services
=========================================
Generates Flask blueprints to expose unified services via API routes

Author: Arkyvus Team
Date: 2026-01-10
"""

import os
import sys
import json
from pathlib import Path
from typing import Dict, List, Any

# Import MAMS config for proper directory structure
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
try:
    from arkyvus.migrations.mams_config import MAMSConfig
except ImportError:
    # Fallback if config not available
    class MAMSConfig:
        BACKEND_BLUEPRINTS_DIR = Path('/app/arkyvus/blueprints/unified')
        @classmethod
        def initialize_directories(cls):
            pass


BLUEPRINT_TEMPLATE = '''"""
Flask Blueprint for {service_name}
Auto-generated by MAMS Blueprint Generator
"""

from flask import Blueprint, jsonify, request
from arkyvus.api.decorators import api_access
from arkyvus.services.{service_module} import {service_class}
from arkyvus.utils.debug_logger import debug_log

# Create blueprint
{blueprint_var} = Blueprint(
    '{blueprint_name}',
    __name__,
    url_prefix=None  # Prefix set during registration
)

# Initialize service
{service_var} = {service_class}()


@{blueprint_var}.route('/health', methods=['GET'])
@api_access()
def health():
    """Health check endpoint"""
    try:
        return jsonify({service_var}.health_check())
    except Exception as e:
        debug_log.error_trace("Health check failed", exception=e)
        return jsonify({{"error": str(e)}}), 500


@{blueprint_var}.route('/info', methods=['GET'])
@api_access()
def info():
    """Service information endpoint"""
    try:
        return jsonify({service_var}.get_info())
    except Exception as e:
        debug_log.error_trace("Info request failed", exception=e)
        return jsonify({{"error": str(e)}}), 500


@{blueprint_var}.route('/ready', methods=['GET'])
@api_access()
def ready():
    """Readiness probe"""
    try:
        return jsonify({service_var}.ready_check())
    except Exception as e:
        return jsonify({{"ready": False, "error": str(e)}}), 503


@{blueprint_var}.route('/metrics', methods=['GET'])
@api_access()
def metrics():
    """Prometheus metrics endpoint"""
    try:
        return jsonify({service_var}.get_metrics())
    except Exception as e:
        debug_log.error_trace("Metrics request failed", exception=e)
        return jsonify({{"error": str(e)}}), 500


# Add service-specific routes based on extracted methods
{additional_routes}
'''

ROUTE_TEMPLATE = '''
@{blueprint_var}.route('/{endpoint}', methods=[{methods}])
@api_access()
def {function_name}():
    """{docstring}"""
    try:
        # Get request data
        data = request.get_json() if request.method == 'POST' else request.args.to_dict()
        
        # Call service method
        result = {service_var}.{method_name}(data)
        
        return jsonify(result)
    except Exception as e:
        debug_log.error_trace("{method_name} failed", exception=e)
        return jsonify({{"error": str(e)}}), 500
'''


def generate_blueprint(service_name: str, service_info: Dict[str, Any]) -> str:
    """
    Generate Flask blueprint for a unified service
    
    Args:
        service_name: Name of the unified service (e.g., 'auth', 'analytics')
        service_info: Service metadata including methods and endpoints
    
    Returns:
        Generated blueprint Python code
    """
    # Naming conventions
    service_class = f"Unified{service_name.capitalize()}Service"
    service_module = f"unified.{service_name}_service"
    service_var = f"{service_name}_service"
    blueprint_var = f"unified_{service_name}_bp"
    blueprint_name = f"unified_{service_name}"
    
    # Check if service is in unified/ subdir or main dir
    if Path(f'/app/arkyvus/services/unified/{service_name}_service.py').exists():
        service_module = f"unified.{service_name}_service"
    elif Path(f'/app/arkyvus/services/unified_{service_name}_service.py').exists():
        service_module = f"unified_{service_name}_service"
    else:
        # Try to find the service
        service_module = f"unified_{service_name}_service"
    
    # Generate additional routes based on service methods
    additional_routes = []
    
    # Common service endpoints based on category
    service_endpoints = {
        'auth': [
            ('login', 'POST', 'User login'),
            ('logout', 'POST', 'User logout'),
            ('verify', 'GET', 'Verify token'),
            ('refresh', 'POST', 'Refresh token'),
        ],
        'analytics': [
            ('metrics', 'GET', 'Get analytics metrics'),
            ('events', 'POST', 'Track events'),
            ('reports', 'GET', 'Generate reports'),
        ],
        'ai': [
            ('generate', 'POST', 'Generate AI content'),
            ('analyze', 'POST', 'Analyze content'),
            ('optimize', 'POST', 'Optimize content'),
        ],
        'storage': [
            ('upload', 'POST', 'Upload file'),
            ('download', 'GET', 'Download file'),
            ('list', 'GET', 'List files'),
            ('delete', 'DELETE', 'Delete file'),
        ],
        'workflow': [
            ('create', 'POST', 'Create workflow'),
            ('execute', 'POST', 'Execute workflow'),
            ('status', 'GET', 'Get workflow status'),
            ('list', 'GET', 'List workflows'),
        ],
    }
    
    # Add service-specific routes
    endpoints = service_endpoints.get(service_name, [])
    for endpoint, method, docstring in endpoints:
        function_name = f"{service_name}_{endpoint}"
        route = ROUTE_TEMPLATE.format(
            blueprint_var=blueprint_var,
            endpoint=endpoint,
            methods=f"'{method}'",
            function_name=function_name,
            docstring=docstring,
            service_var=service_var,
            method_name=endpoint
        )
        additional_routes.append(route)
    
    # Generate complete blueprint
    blueprint_code = BLUEPRINT_TEMPLATE.format(
        service_name=service_name.replace('_', ' ').title(),
        service_module=service_module,
        service_class=service_class,
        blueprint_var=blueprint_var,
        blueprint_name=blueprint_name,
        service_var=service_var,
        additional_routes=''.join(additional_routes)
    )
    
    return blueprint_code


def generate_all_blueprints():
    """Generate blueprints for all unified services"""
    
    # Initialize MAMS directories
    MAMSConfig.initialize_directories()
    
    # Use MAMS blueprint directory  
    blueprint_dir = MAMSConfig.BACKEND_BLUEPRINTS_DIR
    blueprint_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"📁 Generating blueprints in: {blueprint_dir}")
    print(f"⚠️  These are MAMS-generated files, not production!")
    
    # Get list of unified services
    unified_services = []
    
    # Check unified/ subdirectory
    unified_subdir = Path('/app/arkyvus/services/unified')
    if unified_subdir.exists():
        for service_file in unified_subdir.glob('*_service.py'):
            service_name = service_file.stem.replace('_service', '')
            unified_services.append(service_name)
    
    # Check main directory for unified_* files
    services_dir = Path('/app/arkyvus/services')
    for service_file in services_dir.glob('unified_*_service.py'):
        service_name = service_file.stem.replace('unified_', '').replace('_service', '')
        if service_name not in unified_services:
            unified_services.append(service_name)
    
    print(f"📘 Generating blueprints for {len(unified_services)} unified services...")
    
    # Generate blueprint for each service
    generated = []
    for service_name in unified_services:
        try:
            blueprint_code = generate_blueprint(service_name, {})
            
            # Write blueprint file
            blueprint_file = blueprint_dir / f"{service_name}_bp.py"
            with open(blueprint_file, 'w') as f:
                f.write(blueprint_code)
            
            generated.append(service_name)
            print(f"  ✅ Generated blueprint for {service_name}")
            
        except Exception as e:
            print(f"  ❌ Failed to generate blueprint for {service_name}: {e}")
    
    # Create __init__.py for easy import
    init_file = blueprint_dir / '__init__.py'
    init_content = '''"""
Unified Service Blueprints
Auto-generated by MAMS
"""

'''
    
    for service_name in generated:
        init_content += f"from .{service_name}_bp import unified_{service_name}_bp\n"
    
    init_content += f"\n__all__ = [{', '.join([f'\"unified_{s}_bp\"' for s in generated])}]\n"
    
    with open(init_file, 'w') as f:
        f.write(init_content)
    
    print(f"\n✅ Successfully generated {len(generated)} blueprints in /arkyvus/blueprints/unified/")
    
    # Generate app.py integration code
    generate_app_integration(generated)
    
    return generated


def generate_app_integration(service_names: List[str]):
    """Generate code snippet for app.py integration"""
    
    integration_file = Path('/app/.migration/app_integration.py')
    
    code = '''"""
Add this code to app.py to register unified service blueprints
================================================================
"""

# Import unified service blueprints
from arkyvus.blueprints.unified import (
'''
    
    for service_name in service_names:
        code += f"    unified_{service_name}_bp,\n"
    
    code += ''')

def register_unified_blueprints(app):
    """Register all unified service blueprints"""
    
    # API v2 routes for unified services
'''
    
    for service_name in service_names:
        code += f'''    app.register_blueprint(
        unified_{service_name}_bp,
        url_prefix='/api/v2/{service_name.replace("_", "-")}'
    )\n'''
    
    code += '''
    print(f"✅ Registered {len(service_names)} unified service blueprints")

# Call this function in your app initialization
# register_unified_blueprints(app)
'''
    
    with open(integration_file, 'w') as f:
        f.write(code)
    
    print(f"\n📝 Integration code saved to: {integration_file}")
    print("   Add the code to app.py to enable unified service routes")


if __name__ == '__main__':
    generate_all_blueprints()