"""
MAMS Configuration - Defines paths for generated files
========================================================
This ensures MAMS-generated files are kept separate from existing code
to prevent accidental deletion of production services.

Author: Arkyvus Team
Date: 2026-01-11
"""

from pathlib import Path

class MAMSConfig:
    """Configuration for MAMS-generated file locations"""
    
    # Base directory for all MAMS-generated content
    MAMS_BASE_DIR = Path('/Users/pregenie/Development/arkyvus_project/.mams_generated')
    
    # Backend generated services
    BACKEND_SERVICES_DIR = MAMS_BASE_DIR / 'backend' / 'services'
    BACKEND_UNIFIED_DIR = BACKEND_SERVICES_DIR / 'unified'
    BACKEND_BLUEPRINTS_DIR = MAMS_BASE_DIR / 'backend' / 'blueprints'
    BACKEND_ADAPTERS_DIR = MAMS_BASE_DIR / 'backend' / 'adapters'
    
    # Frontend generated files - COMPLETELY SEPARATE from production
    FRONTEND_BASE_DIR = MAMS_BASE_DIR / 'frontend'
    FRONTEND_SERVICES_DIR = FRONTEND_BASE_DIR / 'services' / 'mams_unified'
    FRONTEND_COMPONENTS_DIR = FRONTEND_BASE_DIR / 'components' / 'mams_unified'
    FRONTEND_HOOKS_DIR = FRONTEND_BASE_DIR / 'hooks' / 'mams_unified'
    FRONTEND_TYPES_DIR = FRONTEND_BASE_DIR / 'types' / 'mams_unified'
    FRONTEND_ROUTES_DIR = FRONTEND_BASE_DIR / 'routes' / 'mams_unified'
    FRONTEND_PAGES_DIR = FRONTEND_BASE_DIR / 'pages' / 'mams_unified'
    
    # Migration artifacts
    MIGRATION_DIR = MAMS_BASE_DIR / 'migration'
    MIGRATION_LOGS_DIR = MIGRATION_DIR / 'logs'
    MIGRATION_REPORTS_DIR = MIGRATION_DIR / 'reports'
    MIGRATION_BACKUPS_DIR = MIGRATION_DIR / 'backups'
    
    # Integration files (for manual copying to production)
    INTEGRATION_DIR = MAMS_BASE_DIR / 'integration'
    INTEGRATION_FLASK_FILE = INTEGRATION_DIR / 'flask_integration.py'
    INTEGRATION_REACT_FILE = INTEGRATION_DIR / 'react_integration.md'
    
    @classmethod
    def initialize_directories(cls):
        """Create all required directories"""
        directories = [
            cls.BACKEND_UNIFIED_DIR,
            cls.BACKEND_BLUEPRINTS_DIR,
            cls.BACKEND_ADAPTERS_DIR,
            cls.FRONTEND_SERVICES_DIR,
            cls.FRONTEND_COMPONENTS_DIR,
            cls.FRONTEND_HOOKS_DIR,
            cls.FRONTEND_TYPES_DIR,
            cls.MIGRATION_LOGS_DIR,
            cls.MIGRATION_REPORTS_DIR,
            cls.MIGRATION_BACKUPS_DIR,
            cls.INTEGRATION_DIR
        ]
        
        for directory in directories:
            directory.mkdir(parents=True, exist_ok=True)
        
        # Create README in base directory
        readme_path = cls.MAMS_BASE_DIR / 'README.md'
        if not readme_path.exists():
            readme_content = """# MAMS Generated Files

This directory contains all files generated by the MAMS (Master Automated Migration System).

## ⚠️ IMPORTANT
- These are GENERATED files, not production code
- Do NOT manually edit files in this directory
- Use `ark mams cleanup` to remove these files
- Copy files to production directories only after review

## Directory Structure
- `backend/` - Generated backend services and blueprints
- `frontend/` - Generated React/TypeScript components and services
- `migration/` - Migration logs, reports, and backups
- `integration/` - Integration instructions for production

## Integration Workflow
1. Review generated files in this directory
2. Test the generated code
3. Copy approved files to production directories
4. Update imports and references
5. Remove files from here after integration

Generated by MAMS - Do not edit directly!
"""
            readme_path.write_text(readme_content)
    
    @classmethod
    def get_cleanup_paths(cls):
        """Get all paths that should be cleaned by cleanup command"""
        return [
            cls.BACKEND_SERVICES_DIR,
            cls.BACKEND_BLUEPRINTS_DIR,
            cls.BACKEND_ADAPTERS_DIR,
            cls.FRONTEND_BASE_DIR,
            cls.MIGRATION_BACKUPS_DIR,
            # Note: We keep logs and reports for debugging
        ]
    
    @classmethod
    def is_mams_generated_path(cls, path: Path) -> bool:
        """Check if a path is in MAMS-generated directories"""
        try:
            # Convert to Path object if string
            if isinstance(path, str):
                path = Path(path)
            
            # Check if path is under MAMS base directory
            path.resolve().relative_to(cls.MAMS_BASE_DIR.resolve())
            return True
        except ValueError:
            # Path is not relative to MAMS base directory
            return False
    
    @classmethod
    def get_production_path_mapping(cls):
        """Map MAMS directories to production directories for reference"""
        return {
            cls.BACKEND_UNIFIED_DIR: Path('/Users/pregenie/Development/arkyvus_project/arkyvus/services/unified_mams'),
            cls.BACKEND_BLUEPRINTS_DIR: Path('/Users/pregenie/Development/arkyvus_project/arkyvus/blueprints/unified_mams'),
            cls.FRONTEND_SERVICES_DIR: Path('/Users/pregenie/Development/arkyvus_project/client/src/services/unified_mams'),
            cls.FRONTEND_COMPONENTS_DIR: Path('/Users/pregenie/Development/arkyvus_project/client/src/components/unified_mams'),
        }
    
    @classmethod
    def get_protected_paths(cls):
        """Get list of paths that should NEVER be deleted by cleanup"""
        return [
            # Backend production services
            Path('/Users/pregenie/Development/arkyvus_project/arkyvus/services/unified_*.py'),
            Path('/Users/pregenie/Development/arkyvus_project/arkyvus/services/unified/'),
            Path('/Users/pregenie/Development/arkyvus_project/arkyvus/services/unified_orchestration/'),
            Path('/Users/pregenie/Development/arkyvus_project/arkyvus/services/unified_workflow/'),
            
            # Frontend production components
            Path('/Users/pregenie/Development/arkyvus_project/client/src/components/unified-*'),
            Path('/Users/pregenie/Development/arkyvus_project/client/src/services/unified/'),
            Path('/Users/pregenie/Development/arkyvus_project/client/src/hooks/unified/'),
            Path('/Users/pregenie/Development/arkyvus_project/client/src/types/unified/'),
            Path('/Users/pregenie/Development/arkyvus_project/client/src/pages/unified-*'),
            Path('/Users/pregenie/Development/arkyvus_project/client/src/routes/*Unified*'),
            
            # Critical services that must never be deleted
            Path('/Users/pregenie/Development/arkyvus_project/arkyvus/services/unified_logger.py'),
            Path('/Users/pregenie/Development/arkyvus_project/arkyvus/services/unified_spell_check_service.py'),
            Path('/Users/pregenie/Development/arkyvus_project/arkyvus/services/backup_service.py'),
        ]
    
    @classmethod
    def is_protected_path(cls, path: Path) -> bool:
        """Check if a path is protected from deletion"""
        path_str = str(path.resolve())
        
        # Check against protected patterns
        protected_patterns = [
            # Backend
            'arkyvus/services/unified_',
            'arkyvus/services/unified/',
            'arkyvus/services/unified_orchestration/',
            'arkyvus/services/unified_workflow/',
            
            # Frontend
            'client/src/components/unified-',
            'client/src/services/unified/',
            'client/src/hooks/unified/',
            'client/src/types/unified/',
            'client/src/pages/unified',
            'client/src/routes/',
            
            # Never delete any production service
            'arkyvus/services/',
            'client/src/components/',
        ]
        
        for pattern in protected_patterns:
            if pattern in path_str and 'mams_generated' not in path_str:
                return True
        
        return False